### ISSUE TITLE
Request, redirect for spa development

### ISSUE THREAD

**Issue by braadworst** [slavaGanzin/http2-server#1]
Hey,

was just wondering, is it possible to add a param to the cli like --spa, so all non "/" urls are redirected back to the index.html, this way i can develop my spa without it braking down on refresh on a /some-thing url.

Cheers

**Comment by slavaGanzin** [comment]
@braadworst Will add this soon

**Comment by braadworst** [comment]
Great thanks, any idea when?

**Comment by slavaGanzin** [comment]
@braadworst you can now try new option --proxy your.server.url:port

It will redirect if file can't be served statically.
It works with my angular application

**Comment by braadworst** [comment]
Ace! Try it tomorrow. You having problems with push in chrome?

**Comment by braadworst** [comment]
When I add --proxy

TypeError: Cannot read property 'split' of undefined
    at required (/Users/braadworst/www/vehisell-frontend/node_modules/requires-port/index.js:13:22)
    at Object.common.setupOutgoing (/Users/braadworst/www/vehisell-frontend/node_modules/http-proxy/lib/http-proxy/common.js:102:7)
    at Array.stream (/Users/braadworst/www/vehisell-frontend/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:120:14)
    at ProxyServer.<anonymous> (/Users/braadworst/www/vehisell-frontend/node_modules/http-proxy/lib/http-proxy/index.js:80:21)
    at app.use (/Users/braadworst/www/vehisell-frontend/node_modules/static-http2-server/http2-server:47:8)
    at Layer.handle [as handle_request] (/Users/braadworst/www/vehisell-frontend/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/braadworst/www/vehisell-frontend/node_modules/express/lib/router/index.js:312:13)
    at /Users/braadworst/www/vehisell-frontend/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/braadworst/www/vehisell-frontend/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/braadworst/www/vehisell-frontend/node_modules/express/lib/router/index.js:271:10)

**Comment by braadworst** [comment]
Using node 6.9.5

**Comment by slavaGanzin** [comment]
You should set ```--proxy yourServer:yourPort```, like ```---proxy 127.0.0.1:3000``` for standard express app
and I should add a message for validating proxy parameter
