### ISSUE TITLE
Node.js 12 and above support

### ISSUE THREAD

**Issue by Reon90** [slavaGanzin/http2-server#10]
```
internal/buffer.js:945
class FastBuffer extends Uint8Array {}
^

RangeError: Invalid typed array length: -4095
    at new Uint8Array (<anonymous>)
    at new FastBuffer (internal/buffer.js:945:1)
    at Handle.onStreamRead [as onread] (internal/stream_base_commons.js:185:19)
    at Stream.<anonymous> (/usr/local/lib/node_modules/static-http2-server/node_modules/handle-thing/lib/handle.js:120:12)
    at Stream.emit (events.js:333:22)
    at endReadableNT (/usr/local/lib/node_modules/static-http2-server/node_modules/readable-stream/lib/_stream_readable.js:1010:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by slavaGanzin** [comment]
Thanks for report. This is an error in spdy package:
https://github.com/spdy-http2/node-spdy/issues/363

And it seems they wouldn't fix it.

**Comment by dotnetCarpenter** [comment]
@slavaGanzin How 'bout dropping spdy support and only use http2? Does spdy got any advantage over http2?

**Comment by slavaGanzin** [comment]
@dotnetCarpenter Sure it would be preferable to get native package to work. But it's main interface is stream, while spdy has the same as http/https modules. So it should be some work.

I'm not really committed to opensource right now, so if someone will make PR i'll merge and publish.

**Comment by StephanBijzitter** [comment]
It's been fixed in spdy, see https://github.com/spdy-http2/node-spdy/issues/363#issuecomment-655685032 for more informatiom

**Comment by meszaros-lajos-gyorgy** [comment]
I've just installed the package clean from npm and got this message on the first run, though my error points to line 940

![image](https://user-images.githubusercontent.com/2386064/89687508-a6ce8080-d900-11ea-8a47-c4fd8eac2b2c.png)
