### ISSUE TITLE
Error when try to open page in chrome 

### ISSUE THREAD

**Issue by cevek** [slavaGanzin/http2-server#12]
open url https://localhost:4443

RangeError: Invalid typed array length: -4095
    at new Uint8Array (<anonymous>)
    at new FastBuffer (internal/buffer.js:951:1)
    at Handle.onStreamRead [as onread] (internal/stream_base_commons.js:187:19)
    at Stream.<anonymous> (/usr/local/lib/node_modules/static-http2-server/node_modules/handle-thing/lib/handle.js:120:12)
    at Stream.emit (events.js:327:22)
    at endReadableNT (/usr/local/lib/node_modules/static-http2-server/node_modules/readable-stream/lib/_stream_readable.js:1010:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

**Comment by YannDuv** [comment]
Reproduced also with node 14
Not a fix, but it works with node 10.
