### ISSUE TITLE
Got RST: REFUSED_STREAM

### ISSUE THREAD

**Issue by FlorianKoerner** [slavaGanzin/http2-server#5]
Sometimes I get the following error:

```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Got RST: REFUSED_STREAM
    at Stream._handleRST (/Volumes/Development/css/node_modules/spdy-transport/lib/spdy-transport/stream.js:281:24)
    at Stream._handleFrame (/Volumes/Development/css/node_modules/spdy-transport/lib/spdy-transport/stream.js:126:10)
    at Connection._handleFrame (/Volumes/Development/css/node_modules/spdy-transport/lib/spdy-transport/connection.js:324:12)
    at Parser.<anonymous> (/Volumes/Development/css/node_modules/spdy-transport/lib/spdy-transport/connection.js:156:10)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at addChunk (/Volumes/Development/css/node_modules/readable-stream/lib/_stream_readable.js:284:12)
    at readableAddChunk (/Volumes/Development/css/node_modules/readable-stream/lib/_stream_readable.js:271:11)
    at Parser.Readable.push (/Volumes/Development/css/node_modules/readable-stream/lib/_stream_readable.js:238:10)
    at Parser.Transform.push (/Volumes/Development/css/node_modules/readable-stream/lib/_stream_transform.js:146:32)
```

**Comment by slavaGanzin** [comment]
Hello.
As you can see this is an error in [spdy transport](https://github.com/spdy-http2/spdy-transport)

They had an issue: https://github.com/spdy-http2/node-spdy/issues/266 and it's closed. I think they would be happy if you specify some STR's for this bug and reopen it.

If I can find a way to prevent crushing server on this error, I'll do. But it isn't an issue in http2-server.

**Comment by RezaErfani67** [comment]
can you please make this package with native http2 module in nodejs?
